
services:
  api:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./client/src:/app/src